version: "3.9"

services:
  database:
    image: postgres
    container_name: csv_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DOCKER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DOCKER}
      - POSTGRES_DB=${POSTGRES_DB_DOCKER}
    volumes:
      - ./data/csvdata:/var/lib/postgresql/data
